project:
  type: website
  output-dir: docs

website:
  title: ""
  navbar:
    background: white
    left:
      - href: index.qmd
        text: Home
      - href: Projects.qmd
        text: Projects
      - href: Research.qmd
        text: Research
      - href: Visuals.qmd
        text: Visuals
      - href: Questions.qmd
        text: Questions

  page-footer:
    left: |
      &copy; Elinai Alicia Severiano Perez, 2023<br>
      All content licensed under <i class='bi-badge-cc'></i>
      [(CC BY-NC-SA 4.0)](http://creativecommons.org/licenses/by-nc-sa/4.0/)
    right: |
      Site built with <a href='https://quarto.org/'>Quarto</a>

format:
  html:
    theme: styles.scss
    mainfont: 'Bellota Text'
    toc: true

editor: visual
